# Generated by Django 5.0.3 on 2024-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
