# Generated by Django 5.0.3 on 2024-04-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_id_student_unique_cid_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.CharField(max_length=10),
        ),
    ]
