# Generated by Django 5.0.3 on 2024-04-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='midterm 1', max_length=255),
            preserve_default=False,
        ),
    ]
