# Generated by Django 5.0.3 on 2024-04-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_outcome_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
