# Generated by Django 5.0.3 on 2024-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_outcome_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='number',
            field=models.IntegerField(default=1.1),
            preserve_default=False,
        ),
    ]
