# Generated by Django 5.0.3 on 2024-04-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_outcome_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='number',
            field=models.FloatField(),
        ),
    ]
