# Generated by Django 5.0.3 on 2024-04-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_outcome_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('cid', 'name'), name='unique_cid_name'),
        ),
    ]
