# Generated by Django 5.0.3 on 2024-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_activity_unique_cid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='cid',
            field=models.CharField(max_length=10),
        ),
    ]
