# Generated by Django 5.0.3 on 2024-04-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_activity_cid_alter_outcome_cid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activity',
            name='unique_cid_name',
        ),
    ]
