# Generated by Django 5.0.3 on 2024-04-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_activity_unique_cid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='activity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
