# Generated by Django 5.0.3 on 2024-04-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_outcome_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='aid',
        ),
    ]
