# Generated by Django 5.0.3 on 2024-04-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_grade_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
            preserve_default=False,
        ),
    ]
