# Generated by Django 5.0.3 on 2024-04-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_grade_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cid',
            field=models.CharField(max_length=10),
        ),
    ]
