# Generated by Django 5.0.3 on 2024-04-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_grade_cid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_cid_student_id',
        ),
    ]
